package com.ledger.pay.enums;

public enum EventType {
    TRANSFER_COMPLETED,
    TRANSFER_FAILED,
    DEPOSIT_COMPLETED,
    WITHDRAWAL_COMPLETED,
    SAGA_STARTED,
    SAGA_STEP_REQUESTED,
    SAGA_STEP_COMPLETED,
    SAGA_STEP_FAILED,
    SAGA_COMPLETED,
    SAGA_COMPENSATION_REQUESTED,
    SAGA_FAILED
}
